### ISSUE TITLE
It's not working, and I don't understand what's the reason?

### ISSUE THREAD

**Issue by qq1209974887** [cipchk/ngx-bootstrap-modal#10]
![koown0w54hxkcvxo10z _4](https://user-images.githubusercontent.com/18743063/37949634-06d1b516-31c8-11e8-82e1-4321a717a2e4.png)

It's not working, and I don't understand what's the reason。

**Comment by cipchk** [comment]
angular4 use `1.0.12`
angular5 use `2.x`
