### ISSUE TITLE
这个modal的弹窗如何默认--英语显示 取消 按钮 跟确认按钮啊。

### ISSUE THREAD

**Issue by tokaika** [cipchk/ngx-bootstrap-modal#11]
this.dialogService.confirm('Tips', 'Are you  sure?', <BuiltInOptions>{
      // 可选项，可以对部分参数重写
      "cancelButtonText": "Cancel",
  }).then((result: boolean) => {
      // result
  });``

这样可以显示出来英语。。我看了demo 里面 （https://cipchk.github.io/ngx-bootstrap-modal/）
可以默认显示英语？ 这个有默认配置吗？

**Comment by cipchk** [comment]
参数全局默认参数覆盖 https://github.com/cipchk/ngx-bootstrap-modal/blob/master/src/app/app.module.ts#L25

**Comment by tokaika** [comment]
还有 一个问题。。就是 我弹出框 弹出以后。。默认吗这个弹框的信息都console.log（）出来了。。还请大神指教。。。。。

`e.
ngx-bootstrap-modal.umd.js:424 
{type: "confirm", size: "sm", input: "text", inputOptions: {…}, inputAttributes: {…}, …}
cancelButtonClass
:
"btn-default"
cancelButtonText
:
"Cancel"
confirmButtonClass
:
"btn-primary"
confirmButtonText
:
"Ok"
content
:
"Are you sure to delete it ?"
input
:
"text"
inputAttributes
:
{}
inputOptions
:
{}
inputValue
:
""
onHide
:
ƒ (res)
showCancelButton
:
true
showCloseButton
:
true
showConfirmButton
:
true
size
:
"sm"
title
:
"Tips"
type
:
"confirm"
__proto__
:
Object`

**Comment by cipchk** [comment]
恩，不小心写上了 https://github.com/cipchk/ngx-bootstrap-modal/blob/master/lib/components/built-in.dialog.ts#L136 

下一版本会修复它。

**Comment by tokaika** [comment]
好的。。感谢。。
