### ISSUE TITLE
引入失败，提示“ExpressionChangedAfterItHasBeenCheckedError...”

### ISSUE THREAD

**Issue by qq1209974887** [cipchk/ngx-bootstrap-modal#13]
错误提示：
![image](https://user-images.githubusercontent.com/18743063/47982904-6c70f780-e10c-11e8-87d1-77738a8925ba.png)

使用：
![image](https://user-images.githubusercontent.com/18743063/47982964-ab06b200-e10c-11e8-9352-ead506ad48ed.png)
![image](https://user-images.githubusercontent.com/18743063/47982930-8c082000-e10c-11e8-84c5-42860c60b7b1.png)

版本：
![image](https://user-images.githubusercontent.com/18743063/47982993-c5409000-e10c-11e8-9427-5dd5f77f4e5d.png)

**Comment by cipchk** [comment]
这个错误并不是引入的问题，而是你在 `constructor` 时做了初始化之类的，一般都是由于未正确使用引起的。

**Comment by qq1209974887** [comment]
嗯，是这样的。可是这个DialogServiceConfig接口被识别为类型错误，document.body是符合HTMLElement类型的呀。
![image](https://user-images.githubusercontent.com/18743063/47984090-6bda6000-e110-11e8-9568-df932ebae309.png)
