### ISSUE TITLE
ERROR in Error: Metadata version mismatch for module ../node_modules/ngx-bootstrap-modal/index.d.ts, found version 4, expected 3, resolving symbol 

### ISSUE THREAD

**Issue by jenkyjeni** [cipchk/ngx-bootstrap-modal#4]
Please help me to resolve this in angular 4. This issue occurs with latest version on angular 4

**Comment by cipchk** [comment]
please provider your `package.json`.

or, trying use:

```json
"ngx-bootstrap-modal": "1.0.12"
```

**Comment by jenkyjeni** [comment]
thanks it working fine in 1.0.12

**Comment by Nyantahi** [comment]
Thank you changing to version 1.0.12 worked for me as well.

**Comment by AakritiGoyal** [comment]
Getting same issue with "ngx-bootstrap-modal": "1.0.12"

**Comment by aakritiOpallios** [comment]
Please let me know how to fix this

**Comment by cipchk** [comment]
@aakritiOpallios Please remove `node_modules` & `package_lock.json`.

**Comment by AakritiGoyal** [comment]
Working fine now .. I had to remove ^ from the version

**Comment by AakritiGoyal** [comment]
I am trying to customize alerts but not able to do it ... Title is not visible .. and close button is also not available.. I am using this: 

`title = "success"
        message = "successfully updated"
        this.dialogService.alert(title, message, {
          "icon": icon,
          "size": 'sm',
          "showCancelButton": false,
          "showConfirmButton": false,
          "showCloseButton": true,
        })`

**Comment by cipchk** [comment]
a [demo](https://stackblitz.com/edit/ngx-bootstrap-modal-m3gdmc?file=app/app.component.ts)
  
---
updated

**Comment by aakritiOpallios** [comment]
The page you provided couldn't be found.

**Comment by aakritiOpallios** [comment]
ok I think we can use only one either title or icon.. that's ok but why the close button is not visible when we have set it true in json

**Comment by cipchk** [comment]
I don't think any problem, a shots:

![tim 20180109193938](https://user-images.githubusercontent.com/2987467/34719218-da9c03b4-f574-11e7-82ae-6decfebc7928.png)

**Comment by aakritiOpallios** [comment]
![image](https://user-images.githubusercontent.com/29971381/34719313-59e2b47a-f560-11e7-9007-d0485567402a.png)

Can't we get a close button `(OK)` like this ?

**Comment by cipchk** [comment]
I think stop discussing for the issues, should be new issues if you have any question.
BTW: Please provider a online demo via stackblitz.
