### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by Nangxif** [cipchk/ngx-bootstrap-modal#5]
Why？
Metadata version mismatch for module C:/Users/ASUS/Desktop/angular/App/node_modules/ngx-bootstrap-modal/index.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/Users/ASUS/Desktop/angular/App/src/app/app.module.ts, resolving symbol AppModule in C:/Users/ASUS/Desktop/angular/App/src/app/app.module.ts

**Comment by cipchk** [comment]
duplicated #4
