### ISSUE TITLE
Metadata version mismatch for module - found version 4, expected 3

### ISSUE THREAD

**Issue by AakritiGoyal** [cipchk/ngx-bootstrap-modal#6]
I am getting an error when using ngx-bootstrap-model. 

`ERROR in Error: Metadata version mismatch for module F:/Aakriti/Interbill/Learning/Routing and Navigation/Routes/node_modules/ngx-bootstrap-modal/index.d.ts, found version 4, expected 3, resolving symbol AppModule in F:/Aakriti/Interbill/Learning/Routing and Navigation/Routes/src/app/app.module.ts, resolving symbol AppModule in F:/Aakriti/Interbill/Learning/Routing and Navigation/Routes/src/app/app.module.ts, resolving symbol AppModule in F:/Aakriti/Interbill/Learning/Routing and Navigation/Routes/src/app/app.module.ts`

I am using angular 4.  Any ideas?

**Comment by cipchk** [comment]
duplicated of #4
