### ISSUE TITLE
Any option to show only one modal at a time

### ISSUE THREAD

**Issue by AakritiGoyal** [cipchk/ngx-bootstrap-modal#7]
Hi. I am trying to use ngx-bootstrap-modal to display error messages. I would like to display only one error at a time. Is there any option to display only one modal.. I dont want to open another modal if one is opened already .. Is there any way to achieve this using ngx-bootstrap-modal ?

**Comment by cipchk** [comment]
sorry, i don't catch your meaning.

**Comment by AakritiGoyal** [comment]
I am working with angular 4 and on a page I need to call multiple web services suppose 4-5... Now I am using ngx-bootstrap-modal to display errors .. what happens if i got an error in first call then it will open a modal and a new modal is opened for all the errors so in last I will have 4-5 open modals for all errors .. I need to display only one error.. If a modal is already opened then it should not open a new one

**Comment by cipchk** [comment]
i'm sorry, not yet!

**Comment by AakritiGoyal** [comment]
it's ok np
