### ISSUE TITLE
angular5 下不能打开自定义组件

### ISSUE THREAD

**Issue by kerrph** [cipchk/ngx-bootstrap-modal#8]
![snipaste_2018-01-15_17-24-56](https://user-images.githubusercontent.com/35449819/34935521-26e57c34-fa19-11e7-852b-f67958996f3b.png)

之前的版本在angular4的环境下是正常的。
也配置了entryComponents

**Comment by cipchk** [comment]
能否通过 https://stackblitz.com/edit/ngx-bootstrap-modal 重现一个在线示例吗？

**Comment by kerrph** [comment]
写了个例子没有成功
https://stackblitz.com/edit/ngx-bootstrap-modal-1bkq49

**Comment by cipchk** [comment]
确认一下你的代码：

```html
@Component({
  selector: 'app-custom',
  templateUrl: `<div class="modal-dialog">
````

应该是 `template` 而不是 `templateUrl`

**Comment by kerrph** [comment]
不好意思
